config/routes.rb
Rails.application.routes.draw do

root 'pages#home'

get '/home', to: 'pages#home'

resources :recipes do
	member do
		post 'like'

	end
	resources :reviews
end

resources :chefs, except: [:new, :destroy]


get '/register', to: 'chefs#new'

get '/login', to: "logins#new"
post '/login', to: "logins#create"
get '/logout', to: "logins#destroy"

resources :styles, only: [:new, :create, :show]
resources :ingredients, only: [:new, :create, :show]

end

app/views/pages/home.html.erb
<body class = "spoon">
<!-- using bootstrap class for styling -->
<div class= "center" "jumbotron" >

	<h1>Welcome to Cookin</h1>

	<h2>Interested? Sign up and add your favorite recipe.</h2>

	<%= link_to "Sign up", register_path, class: "btn btn-lg border-blue-join" %>
</div>
<div class="row">
	<div class="col-lg-4">
		<h3 class="midrow">View Recipes As Guest User</h3>
		<h2 class="left">Browse and View Recipes as A Guest and Sign Up Later</h2>
		<p><%= link_to "Browse Recipe Listings", recipes_path, class: "btn btn-warning btn-small border-blue-browse"%></p>
	</div>
		<div class="col-lg-4">
		<h3 class="midrow">Log in to your account</h3>
		<h2 class="left">Add/Update your recipes | Write Reviews | Like/Dislike Recipes </h2>
		<p><%= link_to "Log In", login_path, class: "btn btn-warning btn-small border-blue-browse"%></p>
	</div>
		<div class="col-lg-4">
		<h3 class="midrow">Still working on this</h3>
		<h2 class="left">Cool API Area is coming soon</h2>
		<p><%= link_to "", class: "btn border-blue-browse btn-small"%></p>
	</div>
</div>
</body>